# Generated by Django 2.2.5 on 2020-01-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=255)),
                ('noofdays', models.IntegerField(max_length=255)),
                ('choose_type', models.SmallIntegerField(default=1)),
                ('payment_method', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
