# Generated by Django 2.2.5 on 2020-01-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdetails',
            name='noofdays',
            field=models.IntegerField(),
        ),
    ]
